export type ChatEvent =
  | MessageCreatedEvent
  | MessageEditedEvent
  | MessageDeletedEvent
  | MessagesDeletedEvent
  | ChapterCreatedEvent
  | ChapterEditedEvent
  | ChapterDeletedEvent
  | BookCreatedEvent
  | BookEditedEvent
  | BookDeletedEvent
  | CivitJobCreatedEvent
  | StoryCreatedEvent
  | StoryEditedEvent
  | PlanCreatedEvent
  | PlanHiddenEvent;

export interface MessageCreatedEvent {
  type: "MessageCreated";
  messageId: string;
  role: "assistant" | "user" | "system";
  content: string;
}

export interface MessageEditedEvent {
  type: "MessageEdited";
  messageId: string;
  newContent: string;
}

export interface MessageDeletedEvent {
  type: "MessageDeleted";
  messageId: string;
}

export interface MessagesDeletedEvent {
  type: "MessagesDeleted";
  messageIds: string[];
}

export interface ChapterCreatedEvent {
  type: "ChapterCreated";
  chapterId: string;
  title: string;
  summary: string;
  nextChapterDirection?: string;
  coveredMessageIds: string[];
}

export interface ChapterEditedEvent {
  type: "ChapterEdited";
  chapterId: string;
  title: string;
  summary: string;
  nextChapterDirection?: string;
}

export interface ChapterDeletedEvent {
  type: "ChapterDeleted";
  chapterId: string;
}

export interface CivitJobCreatedEvent {
  type: "CivitJobCreated";
  jobId: string;
  prompt: string;
}

export interface StoryCreatedEvent {
  type: "StoryCreated";
  storyId: string;
  content: string;
}

export interface StoryEditedEvent {
  type: "StoryEdited";
  storyId: string;
  content: string;
}

/**
 * Creates a plan message in the chat timeline.
 * Plans are generated by the LLM and appear as distinct messages in the conversation.
 * Each plan instance is linked to a plan definition via planDefinitionId.
 */
export interface PlanCreatedEvent {
  type: "PlanCreated";
  messageId: string;
  planDefinitionId: string;
  planName: string;
  content: string;
}

/**
 * Hides all previous plan messages for a given plan definition.
 * When a new plan is generated, prior instances are hidden (not deleted)
 * so they no longer appear in the chat but remain in the event history.
 */
export interface PlanHiddenEvent {
  type: "PlanHidden";
  planDefinitionId: string;
}

/**
 * Creates a book that summarizes a contiguous group of chapters.
 * Books compress multiple chapters into a single summary,
 * similar to how chapters compress individual messages.
 */
export interface BookCreatedEvent {
  type: "BookCreated";
  bookId: string;
  title: string;
  summary: string;
  coveredChapterIds: string[];
}

export interface BookEditedEvent {
  type: "BookEdited";
  bookId: string;
  title: string;
  summary: string;
}

export interface BookDeletedEvent {
  type: "BookDeleted";
  bookId: string;
}
